- name: Debian - Install Mysql Server
  apt: 
    name: mariadb-server
    state: present
    
- name: Change to index.php
  shell: sudo sed -i 's/bind-address            = 127.0.0.1/#bind-address            = 127.0.0.1/g' /etc/mysql/mariadb.conf.d/50-server.cnf

- name: Copy files
  copy:
    src: db/
    dest: /tmp/
  
- name: Debian - Start and Enable Mysql Server
  service:
    name: mariadb
    state: restarted
    enabled: true

- name: Debian - Collect package information
  package_facts:
    manager: auto

- name: Debian - Open Mysql Port in the Firewall
  ufw:
    rule: allow
    port: 3306
    proto: tcp
  when: "'ufw' in ansible_facts.packages"

- name: Import DB
  shell: sudo mysql -uroot </tmp/db_setup.sql
  

