- name: Debian - Install Apache HTTP Server
  apt: 
    name: "{{ item }}"
    state: present
  loop:
    - apache2
    - php
    - php-mysqli

- name: Change to index.php
  shell: sudo sed -i 's/DirectoryIndex index.html index.cgi index.pl index.php index.xhtml index.htm/DirectoryIndex index.php/g' /etc/apache2/mods-available/dir.conf

- name: Copy files
  copy:
    src: web/
    dest: /var/www/html/
    
- name: Debian - Start and Enable Apache HTTP Server
  service:
    name: apache2
    state: restarted
    enabled: true

- name: Debian - Collect package information
  package_facts:
    manager: auto

- name: Debian - Open HTTP Port in the Firewall
  ufw:
    rule: allow
    port: 80
    proto: tcp
  when: "'ufw' in ansible_facts.packages"
  
- name: Change to index.php
  shell: sudo echo "192.168.99.101 db" >> /etc/hosts
